"""Initial schema.

Creates all tables from the ORM metadata. Using ``create_all`` for the initial
revision guarantees the migrated schema matches the models exactly (no drift)
and runs identically on SQLite and PostgreSQL. Subsequent schema changes should
use explicit, autogenerated migrations.

Revision ID: 0001_initial
Revises:
Create Date: 2026-10-04
"""
from __future__ import annotations

from alembic import op

from app.db import Base

# Ensure all models are registered on Base.metadata.
import app.models  # noqa: F401

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
